// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: converse_service.proto
#ifndef GRPC_converse_5fservice_2eproto__INCLUDED
#define GRPC_converse_5fservice_2eproto__INCLUDED

#include "converse_service.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace ConverseServiceGRPC {

class ConverseService final {
 public:
  static constexpr char const* service_full_name() {
    return "ConverseServiceGRPC.ConverseService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status RespondToText(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput& request, ::ConverseServiceGRPC::ConversationResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConverseServiceGRPC::ConversationResponse>> AsyncRespondToText(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConverseServiceGRPC::ConversationResponse>>(AsyncRespondToTextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConverseServiceGRPC::ConversationResponse>> PrepareAsyncRespondToText(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ConverseServiceGRPC::ConversationResponse>>(PrepareAsyncRespondToTextRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void RespondToText(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput* request, ::ConverseServiceGRPC::ConversationResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RespondToText(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ConverseServiceGRPC::ConversationResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ConverseServiceGRPC::ConversationResponse>* AsyncRespondToTextRaw(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ConverseServiceGRPC::ConversationResponse>* PrepareAsyncRespondToTextRaw(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status RespondToText(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput& request, ::ConverseServiceGRPC::ConversationResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConverseServiceGRPC::ConversationResponse>> AsyncRespondToText(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConverseServiceGRPC::ConversationResponse>>(AsyncRespondToTextRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConverseServiceGRPC::ConversationResponse>> PrepareAsyncRespondToText(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ConverseServiceGRPC::ConversationResponse>>(PrepareAsyncRespondToTextRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void RespondToText(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput* request, ::ConverseServiceGRPC::ConversationResponse* response, std::function<void(::grpc::Status)>) override;
      void RespondToText(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ConverseServiceGRPC::ConversationResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ConverseServiceGRPC::ConversationResponse>* AsyncRespondToTextRaw(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ConverseServiceGRPC::ConversationResponse>* PrepareAsyncRespondToTextRaw(::grpc::ClientContext* context, const ::ConverseServiceGRPC::ConversationInput& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_RespondToText_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status RespondToText(::grpc::ServerContext* context, const ::ConverseServiceGRPC::ConversationInput* request, ::ConverseServiceGRPC::ConversationResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_RespondToText() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* context, const ::ConverseServiceGRPC::ConversationInput* request, ::ConverseServiceGRPC::ConversationResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRespondToText(::grpc::ServerContext* context, ::ConverseServiceGRPC::ConversationInput* request, ::grpc::ServerAsyncResponseWriter< ::ConverseServiceGRPC::ConversationResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_RespondToText<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_RespondToText() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::ConverseServiceGRPC::ConversationInput, ::ConverseServiceGRPC::ConversationResponse>(
          [this](::grpc::ServerContext* context,
                 const ::ConverseServiceGRPC::ConversationInput* request,
                 ::ConverseServiceGRPC::ConversationResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->RespondToText(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* context, const ::ConverseServiceGRPC::ConversationInput* request, ::ConverseServiceGRPC::ConversationResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void RespondToText(::grpc::ServerContext* context, const ::ConverseServiceGRPC::ConversationInput* request, ::ConverseServiceGRPC::ConversationResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_RespondToText<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_RespondToText() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* context, const ::ConverseServiceGRPC::ConversationInput* request, ::ConverseServiceGRPC::ConversationResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_RespondToText() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* context, const ::ConverseServiceGRPC::ConversationInput* request, ::ConverseServiceGRPC::ConversationResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRespondToText(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_RespondToText() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->RespondToText(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* context, const ::ConverseServiceGRPC::ConversationInput* request, ::ConverseServiceGRPC::ConversationResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void RespondToText(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RespondToText : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_RespondToText() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::ConverseServiceGRPC::ConversationInput, ::ConverseServiceGRPC::ConversationResponse>(std::bind(&WithStreamedUnaryMethod_RespondToText<BaseClass>::StreamedRespondToText, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_RespondToText() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RespondToText(::grpc::ServerContext* context, const ::ConverseServiceGRPC::ConversationInput* request, ::ConverseServiceGRPC::ConversationResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRespondToText(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ConverseServiceGRPC::ConversationInput,::ConverseServiceGRPC::ConversationResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_RespondToText<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_RespondToText<Service > StreamedService;
};

}  // namespace ConverseServiceGRPC


#endif  // GRPC_converse_5fservice_2eproto__INCLUDED
