// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: image_recognition_service.proto

#include "image_recognition_service.pb.h"
#include "image_recognition_service.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace ImageRecognitionServiceRPC {

static const char* ImageRecognitionService_method_names[] = {
  "/ImageRecognitionServiceRPC.ImageRecognitionService/RecognizeImage",
};

std::unique_ptr< ImageRecognitionService::Stub> ImageRecognitionService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ImageRecognitionService::Stub> stub(new ImageRecognitionService::Stub(channel));
  return stub;
}

ImageRecognitionService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RecognizeImage_(ImageRecognitionService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ImageRecognitionService::Stub::RecognizeImage(::grpc::ClientContext* context, const ::ImageRecognitionServiceRPC::ImageRequest& request, ::ImageRecognitionServiceRPC::ImageResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_RecognizeImage_, context, request, response);
}

void ImageRecognitionService::Stub::experimental_async::RecognizeImage(::grpc::ClientContext* context, const ::ImageRecognitionServiceRPC::ImageRequest* request, ::ImageRecognitionServiceRPC::ImageResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RecognizeImage_, context, request, response, std::move(f));
}

void ImageRecognitionService::Stub::experimental_async::RecognizeImage(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::ImageRecognitionServiceRPC::ImageResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_RecognizeImage_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::ImageRecognitionServiceRPC::ImageResponse>* ImageRecognitionService::Stub::AsyncRecognizeImageRaw(::grpc::ClientContext* context, const ::ImageRecognitionServiceRPC::ImageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ImageRecognitionServiceRPC::ImageResponse>::Create(channel_.get(), cq, rpcmethod_RecognizeImage_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::ImageRecognitionServiceRPC::ImageResponse>* ImageRecognitionService::Stub::PrepareAsyncRecognizeImageRaw(::grpc::ClientContext* context, const ::ImageRecognitionServiceRPC::ImageRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::ImageRecognitionServiceRPC::ImageResponse>::Create(channel_.get(), cq, rpcmethod_RecognizeImage_, context, request, false);
}

ImageRecognitionService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ImageRecognitionService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ImageRecognitionService::Service, ::ImageRecognitionServiceRPC::ImageRequest, ::ImageRecognitionServiceRPC::ImageResponse>(
          std::mem_fn(&ImageRecognitionService::Service::RecognizeImage), this)));
}

ImageRecognitionService::Service::~Service() {
}

::grpc::Status ImageRecognitionService::Service::RecognizeImage(::grpc::ServerContext* context, const ::ImageRecognitionServiceRPC::ImageRequest* request, ::ImageRecognitionServiceRPC::ImageResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ImageRecognitionServiceRPC

