// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_classification_service.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_image_5fclassification_5fservice_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_image_5fclassification_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_image_5fclassification_5fservice_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_image_5fclassification_5fservice_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_image_5fclassification_5fservice_2eproto;
namespace ImageClassificationServiceRPC {
class ImageRequest;
class ImageRequestDefaultTypeInternal;
extern ImageRequestDefaultTypeInternal _ImageRequest_default_instance_;
class ImageResponse;
class ImageResponseDefaultTypeInternal;
extern ImageResponseDefaultTypeInternal _ImageResponse_default_instance_;
}  // namespace ImageClassificationServiceRPC
PROTOBUF_NAMESPACE_OPEN
template<> ::ImageClassificationServiceRPC::ImageRequest* Arena::CreateMaybeMessage<::ImageClassificationServiceRPC::ImageRequest>(Arena*);
template<> ::ImageClassificationServiceRPC::ImageResponse* Arena::CreateMaybeMessage<::ImageClassificationServiceRPC::ImageResponse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ImageClassificationServiceRPC {

enum ImageResponse_State : int {
  ImageResponse_State_SUCCESS = 0,
  ImageResponse_State_MODEL_ERR = 1,
  ImageResponse_State_UNKNOWN = 2,
  ImageResponse_State_ImageResponse_State_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  ImageResponse_State_ImageResponse_State_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool ImageResponse_State_IsValid(int value);
constexpr ImageResponse_State ImageResponse_State_State_MIN = ImageResponse_State_SUCCESS;
constexpr ImageResponse_State ImageResponse_State_State_MAX = ImageResponse_State_UNKNOWN;
constexpr int ImageResponse_State_State_ARRAYSIZE = ImageResponse_State_State_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ImageResponse_State_descriptor();
template<typename T>
inline const std::string& ImageResponse_State_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ImageResponse_State>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ImageResponse_State_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ImageResponse_State_descriptor(), enum_t_value);
}
inline bool ImageResponse_State_Parse(
    const std::string& name, ImageResponse_State* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ImageResponse_State>(
    ImageResponse_State_descriptor(), name, value);
}
// ===================================================================

class ImageRequest :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ImageClassificationServiceRPC.ImageRequest) */ {
 public:
  ImageRequest();
  virtual ~ImageRequest();

  ImageRequest(const ImageRequest& from);
  ImageRequest(ImageRequest&& from) noexcept
    : ImageRequest() {
    *this = ::std::move(from);
  }

  inline ImageRequest& operator=(const ImageRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageRequest& operator=(ImageRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ImageRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ImageRequest* internal_default_instance() {
    return reinterpret_cast<const ImageRequest*>(
               &_ImageRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ImageRequest& a, ImageRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ImageRequest* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ImageRequest* New() const final {
    return CreateMaybeMessage<ImageRequest>(nullptr);
  }

  ImageRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ImageRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ImageRequest& from);
  void MergeFrom(const ImageRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ImageClassificationServiceRPC.ImageRequest";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_5fclassification_5fservice_2eproto);
    return ::descriptor_table_image_5fclassification_5fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTransIdFieldNumber = 1,
    kImageFieldNumber = 2,
  };
  // string trans_id = 1;
  void clear_trans_id();
  const std::string& trans_id() const;
  void set_trans_id(const std::string& value);
  void set_trans_id(std::string&& value);
  void set_trans_id(const char* value);
  void set_trans_id(const char* value, size_t size);
  std::string* mutable_trans_id();
  std::string* release_trans_id();
  void set_allocated_trans_id(std::string* trans_id);
  private:
  const std::string& _internal_trans_id() const;
  void _internal_set_trans_id(const std::string& value);
  std::string* _internal_mutable_trans_id();
  public:

  // string image = 2;
  void clear_image();
  const std::string& image() const;
  void set_image(const std::string& value);
  void set_image(std::string&& value);
  void set_image(const char* value);
  void set_image(const char* value, size_t size);
  std::string* mutable_image();
  std::string* release_image();
  void set_allocated_image(std::string* image);
  private:
  const std::string& _internal_image() const;
  void _internal_set_image(const std::string& value);
  std::string* _internal_mutable_image();
  public:

  // @@protoc_insertion_point(class_scope:ImageClassificationServiceRPC.ImageRequest)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trans_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr image_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_image_5fclassification_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ImageResponse :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ImageClassificationServiceRPC.ImageResponse) */ {
 public:
  ImageResponse();
  virtual ~ImageResponse();

  ImageResponse(const ImageResponse& from);
  ImageResponse(ImageResponse&& from) noexcept
    : ImageResponse() {
    *this = ::std::move(from);
  }

  inline ImageResponse& operator=(const ImageResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ImageResponse& operator=(ImageResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ImageResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ImageResponse* internal_default_instance() {
    return reinterpret_cast<const ImageResponse*>(
               &_ImageResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ImageResponse& a, ImageResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ImageResponse* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ImageResponse* New() const final {
    return CreateMaybeMessage<ImageResponse>(nullptr);
  }

  ImageResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ImageResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ImageResponse& from);
  void MergeFrom(const ImageResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ImageResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ImageClassificationServiceRPC.ImageResponse";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_5fclassification_5fservice_2eproto);
    return ::descriptor_table_image_5fclassification_5fservice_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef ImageResponse_State State;
  static constexpr State SUCCESS =
    ImageResponse_State_SUCCESS;
  static constexpr State MODEL_ERR =
    ImageResponse_State_MODEL_ERR;
  static constexpr State UNKNOWN =
    ImageResponse_State_UNKNOWN;
  static inline bool State_IsValid(int value) {
    return ImageResponse_State_IsValid(value);
  }
  static constexpr State State_MIN =
    ImageResponse_State_State_MIN;
  static constexpr State State_MAX =
    ImageResponse_State_State_MAX;
  static constexpr int State_ARRAYSIZE =
    ImageResponse_State_State_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  State_descriptor() {
    return ImageResponse_State_descriptor();
  }
  template<typename T>
  static inline const std::string& State_Name(T enum_t_value) {
    static_assert(::std::is_same<T, State>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function State_Name.");
    return ImageResponse_State_Name(enum_t_value);
  }
  static inline bool State_Parse(const std::string& name,
      State* value) {
    return ImageResponse_State_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kTransIdFieldNumber = 1,
    kTextFieldNumber = 3,
    kStateFieldNumber = 2,
  };
  // string trans_id = 1;
  void clear_trans_id();
  const std::string& trans_id() const;
  void set_trans_id(const std::string& value);
  void set_trans_id(std::string&& value);
  void set_trans_id(const char* value);
  void set_trans_id(const char* value, size_t size);
  std::string* mutable_trans_id();
  std::string* release_trans_id();
  void set_allocated_trans_id(std::string* trans_id);
  private:
  const std::string& _internal_trans_id() const;
  void _internal_set_trans_id(const std::string& value);
  std::string* _internal_mutable_trans_id();
  public:

  // string text = 3;
  void clear_text();
  const std::string& text() const;
  void set_text(const std::string& value);
  void set_text(std::string&& value);
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  std::string* mutable_text();
  std::string* release_text();
  void set_allocated_text(std::string* text);
  private:
  const std::string& _internal_text() const;
  void _internal_set_text(const std::string& value);
  std::string* _internal_mutable_text();
  public:

  // .ImageClassificationServiceRPC.ImageResponse.State state = 2;
  void clear_state();
  ::ImageClassificationServiceRPC::ImageResponse_State state() const;
  void set_state(::ImageClassificationServiceRPC::ImageResponse_State value);
  private:
  ::ImageClassificationServiceRPC::ImageResponse_State _internal_state() const;
  void _internal_set_state(::ImageClassificationServiceRPC::ImageResponse_State value);
  public:

  // @@protoc_insertion_point(class_scope:ImageClassificationServiceRPC.ImageResponse)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trans_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr text_;
  int state_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_image_5fclassification_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ImageRequest

// string trans_id = 1;
inline void ImageRequest::clear_trans_id() {
  trans_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ImageRequest::trans_id() const {
  // @@protoc_insertion_point(field_get:ImageClassificationServiceRPC.ImageRequest.trans_id)
  return _internal_trans_id();
}
inline void ImageRequest::set_trans_id(const std::string& value) {
  _internal_set_trans_id(value);
  // @@protoc_insertion_point(field_set:ImageClassificationServiceRPC.ImageRequest.trans_id)
}
inline std::string* ImageRequest::mutable_trans_id() {
  // @@protoc_insertion_point(field_mutable:ImageClassificationServiceRPC.ImageRequest.trans_id)
  return _internal_mutable_trans_id();
}
inline const std::string& ImageRequest::_internal_trans_id() const {
  return trans_id_.GetNoArena();
}
inline void ImageRequest::_internal_set_trans_id(const std::string& value) {
  
  trans_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ImageRequest::set_trans_id(std::string&& value) {
  
  trans_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ImageClassificationServiceRPC.ImageRequest.trans_id)
}
inline void ImageRequest::set_trans_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trans_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ImageClassificationServiceRPC.ImageRequest.trans_id)
}
inline void ImageRequest::set_trans_id(const char* value, size_t size) {
  
  trans_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ImageClassificationServiceRPC.ImageRequest.trans_id)
}
inline std::string* ImageRequest::_internal_mutable_trans_id() {
  
  return trans_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ImageRequest::release_trans_id() {
  // @@protoc_insertion_point(field_release:ImageClassificationServiceRPC.ImageRequest.trans_id)
  
  return trans_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ImageRequest::set_allocated_trans_id(std::string* trans_id) {
  if (trans_id != nullptr) {
    
  } else {
    
  }
  trans_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trans_id);
  // @@protoc_insertion_point(field_set_allocated:ImageClassificationServiceRPC.ImageRequest.trans_id)
}

// string image = 2;
inline void ImageRequest::clear_image() {
  image_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ImageRequest::image() const {
  // @@protoc_insertion_point(field_get:ImageClassificationServiceRPC.ImageRequest.image)
  return _internal_image();
}
inline void ImageRequest::set_image(const std::string& value) {
  _internal_set_image(value);
  // @@protoc_insertion_point(field_set:ImageClassificationServiceRPC.ImageRequest.image)
}
inline std::string* ImageRequest::mutable_image() {
  // @@protoc_insertion_point(field_mutable:ImageClassificationServiceRPC.ImageRequest.image)
  return _internal_mutable_image();
}
inline const std::string& ImageRequest::_internal_image() const {
  return image_.GetNoArena();
}
inline void ImageRequest::_internal_set_image(const std::string& value) {
  
  image_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ImageRequest::set_image(std::string&& value) {
  
  image_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ImageClassificationServiceRPC.ImageRequest.image)
}
inline void ImageRequest::set_image(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  image_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ImageClassificationServiceRPC.ImageRequest.image)
}
inline void ImageRequest::set_image(const char* value, size_t size) {
  
  image_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ImageClassificationServiceRPC.ImageRequest.image)
}
inline std::string* ImageRequest::_internal_mutable_image() {
  
  return image_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ImageRequest::release_image() {
  // @@protoc_insertion_point(field_release:ImageClassificationServiceRPC.ImageRequest.image)
  
  return image_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ImageRequest::set_allocated_image(std::string* image) {
  if (image != nullptr) {
    
  } else {
    
  }
  image_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), image);
  // @@protoc_insertion_point(field_set_allocated:ImageClassificationServiceRPC.ImageRequest.image)
}

// -------------------------------------------------------------------

// ImageResponse

// string trans_id = 1;
inline void ImageResponse::clear_trans_id() {
  trans_id_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ImageResponse::trans_id() const {
  // @@protoc_insertion_point(field_get:ImageClassificationServiceRPC.ImageResponse.trans_id)
  return _internal_trans_id();
}
inline void ImageResponse::set_trans_id(const std::string& value) {
  _internal_set_trans_id(value);
  // @@protoc_insertion_point(field_set:ImageClassificationServiceRPC.ImageResponse.trans_id)
}
inline std::string* ImageResponse::mutable_trans_id() {
  // @@protoc_insertion_point(field_mutable:ImageClassificationServiceRPC.ImageResponse.trans_id)
  return _internal_mutable_trans_id();
}
inline const std::string& ImageResponse::_internal_trans_id() const {
  return trans_id_.GetNoArena();
}
inline void ImageResponse::_internal_set_trans_id(const std::string& value) {
  
  trans_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ImageResponse::set_trans_id(std::string&& value) {
  
  trans_id_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ImageClassificationServiceRPC.ImageResponse.trans_id)
}
inline void ImageResponse::set_trans_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trans_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ImageClassificationServiceRPC.ImageResponse.trans_id)
}
inline void ImageResponse::set_trans_id(const char* value, size_t size) {
  
  trans_id_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ImageClassificationServiceRPC.ImageResponse.trans_id)
}
inline std::string* ImageResponse::_internal_mutable_trans_id() {
  
  return trans_id_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ImageResponse::release_trans_id() {
  // @@protoc_insertion_point(field_release:ImageClassificationServiceRPC.ImageResponse.trans_id)
  
  return trans_id_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ImageResponse::set_allocated_trans_id(std::string* trans_id) {
  if (trans_id != nullptr) {
    
  } else {
    
  }
  trans_id_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trans_id);
  // @@protoc_insertion_point(field_set_allocated:ImageClassificationServiceRPC.ImageResponse.trans_id)
}

// .ImageClassificationServiceRPC.ImageResponse.State state = 2;
inline void ImageResponse::clear_state() {
  state_ = 0;
}
inline ::ImageClassificationServiceRPC::ImageResponse_State ImageResponse::_internal_state() const {
  return static_cast< ::ImageClassificationServiceRPC::ImageResponse_State >(state_);
}
inline ::ImageClassificationServiceRPC::ImageResponse_State ImageResponse::state() const {
  // @@protoc_insertion_point(field_get:ImageClassificationServiceRPC.ImageResponse.state)
  return _internal_state();
}
inline void ImageResponse::_internal_set_state(::ImageClassificationServiceRPC::ImageResponse_State value) {
  
  state_ = value;
}
inline void ImageResponse::set_state(::ImageClassificationServiceRPC::ImageResponse_State value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:ImageClassificationServiceRPC.ImageResponse.state)
}

// string text = 3;
inline void ImageResponse::clear_text() {
  text_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ImageResponse::text() const {
  // @@protoc_insertion_point(field_get:ImageClassificationServiceRPC.ImageResponse.text)
  return _internal_text();
}
inline void ImageResponse::set_text(const std::string& value) {
  _internal_set_text(value);
  // @@protoc_insertion_point(field_set:ImageClassificationServiceRPC.ImageResponse.text)
}
inline std::string* ImageResponse::mutable_text() {
  // @@protoc_insertion_point(field_mutable:ImageClassificationServiceRPC.ImageResponse.text)
  return _internal_mutable_text();
}
inline const std::string& ImageResponse::_internal_text() const {
  return text_.GetNoArena();
}
inline void ImageResponse::_internal_set_text(const std::string& value) {
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void ImageResponse::set_text(std::string&& value) {
  
  text_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ImageClassificationServiceRPC.ImageResponse.text)
}
inline void ImageResponse::set_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ImageClassificationServiceRPC.ImageResponse.text)
}
inline void ImageResponse::set_text(const char* value, size_t size) {
  
  text_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ImageClassificationServiceRPC.ImageResponse.text)
}
inline std::string* ImageResponse::_internal_mutable_text() {
  
  return text_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ImageResponse::release_text() {
  // @@protoc_insertion_point(field_release:ImageClassificationServiceRPC.ImageResponse.text)
  
  return text_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ImageResponse::set_allocated_text(std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  text_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:ImageClassificationServiceRPC.ImageResponse.text)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ImageClassificationServiceRPC

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ImageClassificationServiceRPC::ImageResponse_State> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ImageClassificationServiceRPC::ImageResponse_State>() {
  return ::ImageClassificationServiceRPC::ImageResponse_State_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_image_5fclassification_5fservice_2eproto
