// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seq2seq_service.proto

#ifndef PROTOBUF_INCLUDED_seq2seq_5fservice_2eproto
#define PROTOBUF_INCLUDED_seq2seq_5fservice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_seq2seq_5fservice_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_seq2seq_5fservice_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_seq2seq_5fservice_2eproto();
namespace Seq2SeqGRPC {
class ConversationInput;
class ConversationInputDefaultTypeInternal;
extern ConversationInputDefaultTypeInternal _ConversationInput_default_instance_;
class ConversationResponse;
class ConversationResponseDefaultTypeInternal;
extern ConversationResponseDefaultTypeInternal _ConversationResponse_default_instance_;
}  // namespace Seq2SeqGRPC
namespace google {
namespace protobuf {
template<> ::Seq2SeqGRPC::ConversationInput* Arena::CreateMaybeMessage<::Seq2SeqGRPC::ConversationInput>(Arena*);
template<> ::Seq2SeqGRPC::ConversationResponse* Arena::CreateMaybeMessage<::Seq2SeqGRPC::ConversationResponse>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace Seq2SeqGRPC {

enum ConversationResponse_State {
  ConversationResponse_State_SUCCESS = 0,
  ConversationResponse_State_MODEL_ERR = 1,
  ConversationResponse_State_UNKNOWN = 2,
  ConversationResponse_State_ConversationResponse_State_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  ConversationResponse_State_ConversationResponse_State_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool ConversationResponse_State_IsValid(int value);
const ConversationResponse_State ConversationResponse_State_State_MIN = ConversationResponse_State_SUCCESS;
const ConversationResponse_State ConversationResponse_State_State_MAX = ConversationResponse_State_UNKNOWN;
const int ConversationResponse_State_State_ARRAYSIZE = ConversationResponse_State_State_MAX + 1;

const ::google::protobuf::EnumDescriptor* ConversationResponse_State_descriptor();
inline const ::std::string& ConversationResponse_State_Name(ConversationResponse_State value) {
  return ::google::protobuf::internal::NameOfEnum(
    ConversationResponse_State_descriptor(), value);
}
inline bool ConversationResponse_State_Parse(
    const ::std::string& name, ConversationResponse_State* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConversationResponse_State>(
    ConversationResponse_State_descriptor(), name, value);
}
// ===================================================================

class ConversationInput final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Seq2SeqGRPC.ConversationInput) */ {
 public:
  ConversationInput();
  virtual ~ConversationInput();

  ConversationInput(const ConversationInput& from);

  inline ConversationInput& operator=(const ConversationInput& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConversationInput(ConversationInput&& from) noexcept
    : ConversationInput() {
    *this = ::std::move(from);
  }

  inline ConversationInput& operator=(ConversationInput&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ConversationInput& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConversationInput* internal_default_instance() {
    return reinterpret_cast<const ConversationInput*>(
               &_ConversationInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ConversationInput* other);
  friend void swap(ConversationInput& a, ConversationInput& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConversationInput* New() const final {
    return CreateMaybeMessage<ConversationInput>(nullptr);
  }

  ConversationInput* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConversationInput>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConversationInput& from);
  void MergeFrom(const ConversationInput& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConversationInput* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string trans_id = 1;
  void clear_trans_id();
  static const int kTransIdFieldNumber = 1;
  const ::std::string& trans_id() const;
  void set_trans_id(const ::std::string& value);
  #if LANG_CXX11
  void set_trans_id(::std::string&& value);
  #endif
  void set_trans_id(const char* value);
  void set_trans_id(const char* value, size_t size);
  ::std::string* mutable_trans_id();
  ::std::string* release_trans_id();
  void set_allocated_trans_id(::std::string* trans_id);

  // string text = 2;
  void clear_text();
  static const int kTextFieldNumber = 2;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  #if LANG_CXX11
  void set_text(::std::string&& value);
  #endif
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // @@protoc_insertion_point(class_scope:Seq2SeqGRPC.ConversationInput)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr trans_id_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_seq2seq_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ConversationResponse final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Seq2SeqGRPC.ConversationResponse) */ {
 public:
  ConversationResponse();
  virtual ~ConversationResponse();

  ConversationResponse(const ConversationResponse& from);

  inline ConversationResponse& operator=(const ConversationResponse& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConversationResponse(ConversationResponse&& from) noexcept
    : ConversationResponse() {
    *this = ::std::move(from);
  }

  inline ConversationResponse& operator=(ConversationResponse&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ConversationResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConversationResponse* internal_default_instance() {
    return reinterpret_cast<const ConversationResponse*>(
               &_ConversationResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ConversationResponse* other);
  friend void swap(ConversationResponse& a, ConversationResponse& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConversationResponse* New() const final {
    return CreateMaybeMessage<ConversationResponse>(nullptr);
  }

  ConversationResponse* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConversationResponse>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConversationResponse& from);
  void MergeFrom(const ConversationResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConversationResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ConversationResponse_State State;
  static const State SUCCESS =
    ConversationResponse_State_SUCCESS;
  static const State MODEL_ERR =
    ConversationResponse_State_MODEL_ERR;
  static const State UNKNOWN =
    ConversationResponse_State_UNKNOWN;
  static inline bool State_IsValid(int value) {
    return ConversationResponse_State_IsValid(value);
  }
  static const State State_MIN =
    ConversationResponse_State_State_MIN;
  static const State State_MAX =
    ConversationResponse_State_State_MAX;
  static const int State_ARRAYSIZE =
    ConversationResponse_State_State_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  State_descriptor() {
    return ConversationResponse_State_descriptor();
  }
  static inline const ::std::string& State_Name(State value) {
    return ConversationResponse_State_Name(value);
  }
  static inline bool State_Parse(const ::std::string& name,
      State* value) {
    return ConversationResponse_State_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string trans_id = 1;
  void clear_trans_id();
  static const int kTransIdFieldNumber = 1;
  const ::std::string& trans_id() const;
  void set_trans_id(const ::std::string& value);
  #if LANG_CXX11
  void set_trans_id(::std::string&& value);
  #endif
  void set_trans_id(const char* value);
  void set_trans_id(const char* value, size_t size);
  ::std::string* mutable_trans_id();
  ::std::string* release_trans_id();
  void set_allocated_trans_id(::std::string* trans_id);

  // string text = 3;
  void clear_text();
  static const int kTextFieldNumber = 3;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  #if LANG_CXX11
  void set_text(::std::string&& value);
  #endif
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // .Seq2SeqGRPC.ConversationResponse.State state = 2;
  void clear_state();
  static const int kStateFieldNumber = 2;
  ::Seq2SeqGRPC::ConversationResponse_State state() const;
  void set_state(::Seq2SeqGRPC::ConversationResponse_State value);

  // @@protoc_insertion_point(class_scope:Seq2SeqGRPC.ConversationResponse)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr trans_id_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  int state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_seq2seq_5fservice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConversationInput

// string trans_id = 1;
inline void ConversationInput::clear_trans_id() {
  trans_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConversationInput::trans_id() const {
  // @@protoc_insertion_point(field_get:Seq2SeqGRPC.ConversationInput.trans_id)
  return trans_id_.GetNoArena();
}
inline void ConversationInput::set_trans_id(const ::std::string& value) {
  
  trans_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Seq2SeqGRPC.ConversationInput.trans_id)
}
#if LANG_CXX11
inline void ConversationInput::set_trans_id(::std::string&& value) {
  
  trans_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Seq2SeqGRPC.ConversationInput.trans_id)
}
#endif
inline void ConversationInput::set_trans_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trans_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Seq2SeqGRPC.ConversationInput.trans_id)
}
inline void ConversationInput::set_trans_id(const char* value, size_t size) {
  
  trans_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Seq2SeqGRPC.ConversationInput.trans_id)
}
inline ::std::string* ConversationInput::mutable_trans_id() {
  
  // @@protoc_insertion_point(field_mutable:Seq2SeqGRPC.ConversationInput.trans_id)
  return trans_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConversationInput::release_trans_id() {
  // @@protoc_insertion_point(field_release:Seq2SeqGRPC.ConversationInput.trans_id)
  
  return trans_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConversationInput::set_allocated_trans_id(::std::string* trans_id) {
  if (trans_id != nullptr) {
    
  } else {
    
  }
  trans_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), trans_id);
  // @@protoc_insertion_point(field_set_allocated:Seq2SeqGRPC.ConversationInput.trans_id)
}

// string text = 2;
inline void ConversationInput::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConversationInput::text() const {
  // @@protoc_insertion_point(field_get:Seq2SeqGRPC.ConversationInput.text)
  return text_.GetNoArena();
}
inline void ConversationInput::set_text(const ::std::string& value) {
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Seq2SeqGRPC.ConversationInput.text)
}
#if LANG_CXX11
inline void ConversationInput::set_text(::std::string&& value) {
  
  text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Seq2SeqGRPC.ConversationInput.text)
}
#endif
inline void ConversationInput::set_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Seq2SeqGRPC.ConversationInput.text)
}
inline void ConversationInput::set_text(const char* value, size_t size) {
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Seq2SeqGRPC.ConversationInput.text)
}
inline ::std::string* ConversationInput::mutable_text() {
  
  // @@protoc_insertion_point(field_mutable:Seq2SeqGRPC.ConversationInput.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConversationInput::release_text() {
  // @@protoc_insertion_point(field_release:Seq2SeqGRPC.ConversationInput.text)
  
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConversationInput::set_allocated_text(::std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:Seq2SeqGRPC.ConversationInput.text)
}

// -------------------------------------------------------------------

// ConversationResponse

// string trans_id = 1;
inline void ConversationResponse::clear_trans_id() {
  trans_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConversationResponse::trans_id() const {
  // @@protoc_insertion_point(field_get:Seq2SeqGRPC.ConversationResponse.trans_id)
  return trans_id_.GetNoArena();
}
inline void ConversationResponse::set_trans_id(const ::std::string& value) {
  
  trans_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Seq2SeqGRPC.ConversationResponse.trans_id)
}
#if LANG_CXX11
inline void ConversationResponse::set_trans_id(::std::string&& value) {
  
  trans_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Seq2SeqGRPC.ConversationResponse.trans_id)
}
#endif
inline void ConversationResponse::set_trans_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trans_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Seq2SeqGRPC.ConversationResponse.trans_id)
}
inline void ConversationResponse::set_trans_id(const char* value, size_t size) {
  
  trans_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Seq2SeqGRPC.ConversationResponse.trans_id)
}
inline ::std::string* ConversationResponse::mutable_trans_id() {
  
  // @@protoc_insertion_point(field_mutable:Seq2SeqGRPC.ConversationResponse.trans_id)
  return trans_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConversationResponse::release_trans_id() {
  // @@protoc_insertion_point(field_release:Seq2SeqGRPC.ConversationResponse.trans_id)
  
  return trans_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConversationResponse::set_allocated_trans_id(::std::string* trans_id) {
  if (trans_id != nullptr) {
    
  } else {
    
  }
  trans_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), trans_id);
  // @@protoc_insertion_point(field_set_allocated:Seq2SeqGRPC.ConversationResponse.trans_id)
}

// .Seq2SeqGRPC.ConversationResponse.State state = 2;
inline void ConversationResponse::clear_state() {
  state_ = 0;
}
inline ::Seq2SeqGRPC::ConversationResponse_State ConversationResponse::state() const {
  // @@protoc_insertion_point(field_get:Seq2SeqGRPC.ConversationResponse.state)
  return static_cast< ::Seq2SeqGRPC::ConversationResponse_State >(state_);
}
inline void ConversationResponse::set_state(::Seq2SeqGRPC::ConversationResponse_State value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:Seq2SeqGRPC.ConversationResponse.state)
}

// string text = 3;
inline void ConversationResponse::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConversationResponse::text() const {
  // @@protoc_insertion_point(field_get:Seq2SeqGRPC.ConversationResponse.text)
  return text_.GetNoArena();
}
inline void ConversationResponse::set_text(const ::std::string& value) {
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Seq2SeqGRPC.ConversationResponse.text)
}
#if LANG_CXX11
inline void ConversationResponse::set_text(::std::string&& value) {
  
  text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Seq2SeqGRPC.ConversationResponse.text)
}
#endif
inline void ConversationResponse::set_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Seq2SeqGRPC.ConversationResponse.text)
}
inline void ConversationResponse::set_text(const char* value, size_t size) {
  
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Seq2SeqGRPC.ConversationResponse.text)
}
inline ::std::string* ConversationResponse::mutable_text() {
  
  // @@protoc_insertion_point(field_mutable:Seq2SeqGRPC.ConversationResponse.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConversationResponse::release_text() {
  // @@protoc_insertion_point(field_release:Seq2SeqGRPC.ConversationResponse.text)
  
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConversationResponse::set_allocated_text(::std::string* text) {
  if (text != nullptr) {
    
  } else {
    
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:Seq2SeqGRPC.ConversationResponse.text)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Seq2SeqGRPC

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::Seq2SeqGRPC::ConversationResponse_State> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::Seq2SeqGRPC::ConversationResponse_State>() {
  return ::Seq2SeqGRPC::ConversationResponse_State_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_seq2seq_5fservice_2eproto
