// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seq2seq_service.proto

#include "seq2seq_service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace Seq2SeqGRPC {
class ConversationInputDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConversationInput> _instance;
} _ConversationInput_default_instance_;
class ConversationResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConversationResponse> _instance;
} _ConversationResponse_default_instance_;
}  // namespace Seq2SeqGRPC
static void InitDefaultsConversationInput_seq2seq_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Seq2SeqGRPC::_ConversationInput_default_instance_;
    new (ptr) ::Seq2SeqGRPC::ConversationInput();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Seq2SeqGRPC::ConversationInput::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ConversationInput_seq2seq_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsConversationInput_seq2seq_5fservice_2eproto}, {}};

static void InitDefaultsConversationResponse_seq2seq_5fservice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Seq2SeqGRPC::_ConversationResponse_default_instance_;
    new (ptr) ::Seq2SeqGRPC::ConversationResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Seq2SeqGRPC::ConversationResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ConversationResponse_seq2seq_5fservice_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsConversationResponse_seq2seq_5fservice_2eproto}, {}};

void InitDefaults_seq2seq_5fservice_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ConversationInput_seq2seq_5fservice_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ConversationResponse_seq2seq_5fservice_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_seq2seq_5fservice_2eproto[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_seq2seq_5fservice_2eproto[1];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_seq2seq_5fservice_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_seq2seq_5fservice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationInput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationInput, trans_id_),
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationInput, text_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationResponse, trans_id_),
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationResponse, state_),
  PROTOBUF_FIELD_OFFSET(::Seq2SeqGRPC::ConversationResponse, text_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Seq2SeqGRPC::ConversationInput)},
  { 7, -1, sizeof(::Seq2SeqGRPC::ConversationResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Seq2SeqGRPC::_ConversationInput_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Seq2SeqGRPC::_ConversationResponse_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_seq2seq_5fservice_2eproto = {
  {}, AddDescriptors_seq2seq_5fservice_2eproto, "seq2seq_service.proto", schemas,
  file_default_instances, TableStruct_seq2seq_5fservice_2eproto::offsets,
  file_level_metadata_seq2seq_5fservice_2eproto, 2, file_level_enum_descriptors_seq2seq_5fservice_2eproto, file_level_service_descriptors_seq2seq_5fservice_2eproto,
};

const char descriptor_table_protodef_seq2seq_5fservice_2eproto[] =
  "\n\025seq2seq_service.proto\022\013Seq2SeqGRPC\"3\n\021"
  "ConversationInput\022\020\n\010trans_id\030\001 \001(\t\022\014\n\004t"
  "ext\030\002 \001(\t\"\240\001\n\024ConversationResponse\022\020\n\010tr"
  "ans_id\030\001 \001(\t\0226\n\005state\030\002 \001(\0162\'.Seq2SeqGRP"
  "C.ConversationResponse.State\022\014\n\004text\030\003 \001"
  "(\t\"0\n\005State\022\013\n\007SUCCESS\020\000\022\r\n\tMODEL_ERR\020\001\022"
  "\013\n\007UNKNOWN\020\0022d\n\016Seq2SeqService\022R\n\rRespon"
  "dToText\022\036.Seq2SeqGRPC.ConversationInput\032"
  "!.Seq2SeqGRPC.ConversationResponseB\006\242\002\003R"
  "TGb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_seq2seq_5fservice_2eproto = {
  false, InitDefaults_seq2seq_5fservice_2eproto, 
  descriptor_table_protodef_seq2seq_5fservice_2eproto,
  "seq2seq_service.proto", &assign_descriptors_table_seq2seq_5fservice_2eproto, 370,
};

void AddDescriptors_seq2seq_5fservice_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_seq2seq_5fservice_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_seq2seq_5fservice_2eproto = []() { AddDescriptors_seq2seq_5fservice_2eproto(); return true; }();
namespace Seq2SeqGRPC {
const ::google::protobuf::EnumDescriptor* ConversationResponse_State_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_seq2seq_5fservice_2eproto);
  return file_level_enum_descriptors_seq2seq_5fservice_2eproto[0];
}
bool ConversationResponse_State_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ConversationResponse_State ConversationResponse::SUCCESS;
const ConversationResponse_State ConversationResponse::MODEL_ERR;
const ConversationResponse_State ConversationResponse::UNKNOWN;
const ConversationResponse_State ConversationResponse::State_MIN;
const ConversationResponse_State ConversationResponse::State_MAX;
const int ConversationResponse::State_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void ConversationInput::InitAsDefaultInstance() {
}
class ConversationInput::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConversationInput::kTransIdFieldNumber;
const int ConversationInput::kTextFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConversationInput::ConversationInput()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Seq2SeqGRPC.ConversationInput)
}
ConversationInput::ConversationInput(const ConversationInput& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  trans_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.trans_id().size() > 0) {
    trans_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.trans_id_);
  }
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.text().size() > 0) {
    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  // @@protoc_insertion_point(copy_constructor:Seq2SeqGRPC.ConversationInput)
}

void ConversationInput::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ConversationInput_seq2seq_5fservice_2eproto.base);
  trans_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ConversationInput::~ConversationInput() {
  // @@protoc_insertion_point(destructor:Seq2SeqGRPC.ConversationInput)
  SharedDtor();
}

void ConversationInput::SharedDtor() {
  trans_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  text_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ConversationInput::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ConversationInput& ConversationInput::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ConversationInput_seq2seq_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ConversationInput::Clear() {
// @@protoc_insertion_point(message_clear_start:Seq2SeqGRPC.ConversationInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  trans_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ConversationInput::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ConversationInput*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string trans_id = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("Seq2SeqGRPC.ConversationInput.trans_id");
        object = msg->mutable_trans_id();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string text = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("Seq2SeqGRPC.ConversationInput.text");
        object = msg->mutable_text();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ConversationInput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Seq2SeqGRPC.ConversationInput)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string trans_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_trans_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->trans_id().data(), static_cast<int>(this->trans_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Seq2SeqGRPC.ConversationInput.trans_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string text = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_text()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->text().data(), static_cast<int>(this->text().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Seq2SeqGRPC.ConversationInput.text"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Seq2SeqGRPC.ConversationInput)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Seq2SeqGRPC.ConversationInput)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ConversationInput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Seq2SeqGRPC.ConversationInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string trans_id = 1;
  if (this->trans_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->trans_id().data(), static_cast<int>(this->trans_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationInput.trans_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->trans_id(), output);
  }

  // string text = 2;
  if (this->text().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text().data(), static_cast<int>(this->text().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationInput.text");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->text(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Seq2SeqGRPC.ConversationInput)
}

::google::protobuf::uint8* ConversationInput::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Seq2SeqGRPC.ConversationInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string trans_id = 1;
  if (this->trans_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->trans_id().data(), static_cast<int>(this->trans_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationInput.trans_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->trans_id(), target);
  }

  // string text = 2;
  if (this->text().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text().data(), static_cast<int>(this->text().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationInput.text");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->text(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Seq2SeqGRPC.ConversationInput)
  return target;
}

size_t ConversationInput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Seq2SeqGRPC.ConversationInput)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string trans_id = 1;
  if (this->trans_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->trans_id());
  }

  // string text = 2;
  if (this->text().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->text());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConversationInput::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Seq2SeqGRPC.ConversationInput)
  GOOGLE_DCHECK_NE(&from, this);
  const ConversationInput* source =
      ::google::protobuf::DynamicCastToGenerated<ConversationInput>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Seq2SeqGRPC.ConversationInput)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Seq2SeqGRPC.ConversationInput)
    MergeFrom(*source);
  }
}

void ConversationInput::MergeFrom(const ConversationInput& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Seq2SeqGRPC.ConversationInput)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.trans_id().size() > 0) {

    trans_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.trans_id_);
  }
  if (from.text().size() > 0) {

    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
}

void ConversationInput::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Seq2SeqGRPC.ConversationInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConversationInput::CopyFrom(const ConversationInput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Seq2SeqGRPC.ConversationInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConversationInput::IsInitialized() const {
  return true;
}

void ConversationInput::Swap(ConversationInput* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConversationInput::InternalSwap(ConversationInput* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  trans_id_.Swap(&other->trans_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  text_.Swap(&other->text_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
}

::google::protobuf::Metadata ConversationInput::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_seq2seq_5fservice_2eproto);
  return ::file_level_metadata_seq2seq_5fservice_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ConversationResponse::InitAsDefaultInstance() {
}
class ConversationResponse::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConversationResponse::kTransIdFieldNumber;
const int ConversationResponse::kStateFieldNumber;
const int ConversationResponse::kTextFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConversationResponse::ConversationResponse()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Seq2SeqGRPC.ConversationResponse)
}
ConversationResponse::ConversationResponse(const ConversationResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  trans_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.trans_id().size() > 0) {
    trans_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.trans_id_);
  }
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.text().size() > 0) {
    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  state_ = from.state_;
  // @@protoc_insertion_point(copy_constructor:Seq2SeqGRPC.ConversationResponse)
}

void ConversationResponse::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ConversationResponse_seq2seq_5fservice_2eproto.base);
  trans_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  text_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  state_ = 0;
}

ConversationResponse::~ConversationResponse() {
  // @@protoc_insertion_point(destructor:Seq2SeqGRPC.ConversationResponse)
  SharedDtor();
}

void ConversationResponse::SharedDtor() {
  trans_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  text_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ConversationResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ConversationResponse& ConversationResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ConversationResponse_seq2seq_5fservice_2eproto.base);
  return *internal_default_instance();
}


void ConversationResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:Seq2SeqGRPC.ConversationResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  trans_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  state_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ConversationResponse::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ConversationResponse*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string trans_id = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("Seq2SeqGRPC.ConversationResponse.trans_id");
        object = msg->mutable_trans_id();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // .Seq2SeqGRPC.ConversationResponse.State state = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        ::google::protobuf::uint64 val = ::google::protobuf::internal::ReadVarint(&ptr);
        msg->set_state(static_cast<::Seq2SeqGRPC::ConversationResponse_State>(val));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string text = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("Seq2SeqGRPC.ConversationResponse.text");
        object = msg->mutable_text();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ConversationResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Seq2SeqGRPC.ConversationResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string trans_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_trans_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->trans_id().data(), static_cast<int>(this->trans_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Seq2SeqGRPC.ConversationResponse.trans_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Seq2SeqGRPC.ConversationResponse.State state = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_state(static_cast< ::Seq2SeqGRPC::ConversationResponse_State >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string text = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_text()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->text().data(), static_cast<int>(this->text().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Seq2SeqGRPC.ConversationResponse.text"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Seq2SeqGRPC.ConversationResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Seq2SeqGRPC.ConversationResponse)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ConversationResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Seq2SeqGRPC.ConversationResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string trans_id = 1;
  if (this->trans_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->trans_id().data(), static_cast<int>(this->trans_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationResponse.trans_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->trans_id(), output);
  }

  // .Seq2SeqGRPC.ConversationResponse.State state = 2;
  if (this->state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->state(), output);
  }

  // string text = 3;
  if (this->text().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text().data(), static_cast<int>(this->text().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationResponse.text");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->text(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:Seq2SeqGRPC.ConversationResponse)
}

::google::protobuf::uint8* ConversationResponse::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Seq2SeqGRPC.ConversationResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string trans_id = 1;
  if (this->trans_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->trans_id().data(), static_cast<int>(this->trans_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationResponse.trans_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->trans_id(), target);
  }

  // .Seq2SeqGRPC.ConversationResponse.State state = 2;
  if (this->state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->state(), target);
  }

  // string text = 3;
  if (this->text().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->text().data(), static_cast<int>(this->text().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Seq2SeqGRPC.ConversationResponse.text");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->text(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Seq2SeqGRPC.ConversationResponse)
  return target;
}

size_t ConversationResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Seq2SeqGRPC.ConversationResponse)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string trans_id = 1;
  if (this->trans_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->trans_id());
  }

  // string text = 3;
  if (this->text().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->text());
  }

  // .Seq2SeqGRPC.ConversationResponse.State state = 2;
  if (this->state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConversationResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Seq2SeqGRPC.ConversationResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ConversationResponse* source =
      ::google::protobuf::DynamicCastToGenerated<ConversationResponse>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Seq2SeqGRPC.ConversationResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Seq2SeqGRPC.ConversationResponse)
    MergeFrom(*source);
  }
}

void ConversationResponse::MergeFrom(const ConversationResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Seq2SeqGRPC.ConversationResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.trans_id().size() > 0) {

    trans_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.trans_id_);
  }
  if (from.text().size() > 0) {

    text_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.text_);
  }
  if (from.state() != 0) {
    set_state(from.state());
  }
}

void ConversationResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Seq2SeqGRPC.ConversationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConversationResponse::CopyFrom(const ConversationResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Seq2SeqGRPC.ConversationResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConversationResponse::IsInitialized() const {
  return true;
}

void ConversationResponse::Swap(ConversationResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConversationResponse::InternalSwap(ConversationResponse* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  trans_id_.Swap(&other->trans_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  text_.Swap(&other->text_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(state_, other->state_);
}

::google::protobuf::Metadata ConversationResponse::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_seq2seq_5fservice_2eproto);
  return ::file_level_metadata_seq2seq_5fservice_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Seq2SeqGRPC
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::Seq2SeqGRPC::ConversationInput* Arena::CreateMaybeMessage< ::Seq2SeqGRPC::ConversationInput >(Arena* arena) {
  return Arena::CreateInternal< ::Seq2SeqGRPC::ConversationInput >(arena);
}
template<> PROTOBUF_NOINLINE ::Seq2SeqGRPC::ConversationResponse* Arena::CreateMaybeMessage< ::Seq2SeqGRPC::ConversationResponse >(Arena* arena) {
  return Arena::CreateInternal< ::Seq2SeqGRPC::ConversationResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
